import { and, desc, eq, isNull } from "drizzle-orm";
import semver from "semver";
import {
  db,
  deployRuns,
  packageFindings,
  perfRuns,
  repositories,
  scans,
  serverFindings,
  vulnerabilities,
} from "db";
import type { ConfigCheck } from "./config-check";
import type { SiteProbe } from "./site-probe";
import { budgetFailures } from "./perf";

type Repo = typeof repositories.$inferSelect;
type Vuln = typeof vulnerabilities.$inferSelect;
type Pkg = typeof packageFindings.$inferSelect;
type LiveFinding = typeof serverFindings.$inferSelect;
type Deploy = typeof deployRuns.$inferSelect;

export type FindingsData = {
  repo: Pick<
    Repo,
    | "name"
    | "githubUrl"
    | "defaultBranch"
    | "packageJsonPath"
    | "liveUrl"
    | "liveCommit"
    | "liveChecks"
    | "configCheck"
    | "siteProbe"
  >;
  scan: { startedAt: Date; ref: string | null; target: string } | null;
  vulns: Vuln[];
  packages: Pkg[];
  live: LiveFinding[];
  lastDeploy: Deploy | null;
  /** The latest mobile Lighthouse run. */
  perf?: typeof perfRuns.$inferSelect | null;
  generatedAt: Date;
};

const SEVERITY_ORDER = ["critical", "high", "moderate", "low", "info"];

function cell(s: string | null | undefined): string {
  return (s ?? "—").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/**
 * Everything a scan found, as a task list a coding agent can work through:
 * what to change, why, and how to tell it worked. Plain markdown — paste it
 * into Claude Code, Cursor or an issue.
 */
export function renderFindings(d: FindingsData): string {
  const { repo } = d;
  const root =
    repo.packageJsonPath && repo.packageJsonPath !== "package.json"
      ? repo.packageJsonPath.replace(/\/?package\.json$/, "")
      : ".";
  const out: string[] = [];
  out.push(`# Findings: ${repo.name}`);
  out.push("");
  out.push(
    [
      `- Repository: ${repo.githubUrl} (branch \`${repo.defaultBranch}\`, package root \`${root}\`)`,
      d.scan
        ? `- Scanned: ${d.scan.startedAt.toISOString()} — ${d.scan.target === "live" ? `deployed commit \`${d.scan.ref}\`` : `branch \`${d.scan.ref ?? repo.defaultBranch}\``}`
        : "- Scanned: never — run a scan first",
      repo.liveUrl
        ? `- Live: ${repo.liveUrl}${repo.liveCommit ? ` (commit \`${repo.liveCommit}\`)` : ""}`
        : null,
      `- Generated by Moatline: ${d.generatedAt.toISOString()}`,
    ]
      .filter(Boolean)
      .join("\n")
  );
  out.push("");
  out.push("## Instructions for the coding agent");
  out.push("");
  out.push(
    [
      `Work in \`${repo.githubUrl}\` on a new branch from \`${repo.defaultBranch}\`. Fix the items below in order, one commit per section.`,
      "",
      "- Keep the package manager the repository uses (its lockfile) and commit the updated lockfile.",
      "- Stay within each package's major version unless an item says otherwise.",
      "- Payload (`payload` + `@payloadcms/*`), Next.js (`next`, `@next/*`), React (`react`, `react-dom`) and Lexical must each end at one exact version across all their packages — Payload refuses to start otherwise.",
      "- Verify: install, typecheck (`tsc --noEmit`) and build; for Payload, open `/admin` locally.",
      "- Do not touch secrets or `.env` files; configuration items name what to set, not the values.",
    ].join("\n")
  );

  // Vulnerabilities
  out.push("");
  const vulns = [...d.vulns].sort(
    (a, b) =>
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity) ||
      a.packageName.localeCompare(b.packageName)
  );
  out.push(`## 1. Vulnerabilities (${vulns.length})`);
  out.push("");
  if (!vulns.length) {
    out.push(d.scan ? "None known. ✅" : "Not scanned yet.");
  } else {
    const fixable = vulns.filter((v) => v.fixAvailable);
    const unfixable = vulns.filter((v) => !v.fixAvailable);
    if (fixable.length) {
      out.push("Fix by moving each package to at least the fixed version:");
      out.push("");
      for (const v of fixable) {
        const how = v.isDirect
          ? `raise \`${v.packageName}\` in package.json to \`^${v.patchedVersion}\``
          : `transitive — update the parent dependency, or pin \`${v.packageName}\` ≥ \`${v.patchedVersion}\` via overrides (pnpm/npm) or resolutions (yarn)`;
        out.push(
          `- [ ] **${v.severity}** \`${v.packageName}\` ${v.vulnerableRange ?? ""} → fixed in \`${v.patchedVersion}\`${v.fixIsSemverMajor ? " (**major upgrade**: read the changelog)" : ""}: ${how}. ${v.title ?? ""}${v.url ? ` — ${v.url}` : ""}`
        );
      }
    }
    if (unfixable.length) {
      out.push("");
      out.push(
        "No fixed version published yet — assess exposure, replace the package if it is reachable from user input:"
      );
      out.push("");
      for (const v of unfixable)
        out.push(
          `- [ ] **${v.severity}** \`${v.packageName}\` ${v.vulnerableRange ?? ""}: ${v.title ?? ""}${v.url ? ` — ${v.url}` : ""}`
        );
    }
    out.push("");
    out.push(
      "Done when: a fresh audit of the lockfile shows none of the advisories above."
    );
  }

  // Packages
  const outdated = d.packages.filter((p) => {
    const cur = semver.coerce(p.currentVersion);
    const lat = semver.coerce(p.latestVersion);
    return cur && lat && semver.lt(cur, lat);
  });
  const majors = outdated.filter(
    (p) =>
      semver.coerce(p.latestVersion)!.major >
      semver.coerce(p.currentVersion)!.major
  );
  const minors = outdated.filter((p) => !majors.includes(p));
  const unused = d.packages.filter((p) => p.unused);
  out.push("");
  out.push(
    `## 2. Dependencies (${outdated.length} outdated, ${unused.length} unused)`
  );
  out.push("");
  if (minors.length) {
    out.push("- [ ] Minor and patch updates (low risk):");
    out.push("");
    out.push("  | Package | Declared | Latest | Dev |");
    out.push("  | --- | --- | --- | --- |");
    for (const p of minors)
      out.push(
        `  | \`${p.packageName}\` | ${cell(p.wantedVersion ?? p.currentVersion)} | ${cell(p.latestVersion)} | ${p.isDevDependency ? "yes" : ""} |`
      );
    out.push("");
  }
  if (majors.length) {
    out.push(
      "- [ ] Major updates — one at a time, read each changelog, separate commits:"
    );
    out.push("");
    for (const p of majors)
      out.push(
        `  - [ ] \`${p.packageName}\` ${p.wantedVersion ?? p.currentVersion} → ${p.latestVersion}${p.isDevDependency ? " (dev)" : ""}`
      );
    out.push("");
  }
  if (unused.length) {
    out.push(
      `- [ ] Remove unused dependencies (verify with a search first — config files and scripts count): ${unused.map((p) => `\`${p.packageName}\``).join(", ")}`
    );
    out.push("");
  }
  if (!outdated.length && !unused.length) out.push("Nothing to do. ✅");

  // Configuration
  const checks = Object.entries(
    (repo.liveChecks ?? {}) as Record<string, unknown>
  ).filter(([, v]) => v === false);
  const missing = (
    (repo.configCheck as ConfigCheck | null)?.items ?? []
  ).filter((i) => !i.ok);
  out.push("");
  out.push(`## 3. Configuration (${checks.length + missing.length})`);
  out.push("");
  if (!checks.length && !missing.length) {
    out.push(
      repo.liveChecks || repo.configCheck
        ? "Nothing missing. ✅"
        : "Not reported. Add a `checks` object to `/api/health` (see docs/health-endpoint.md) so configuration problems show up."
    );
  }
  for (const [k] of checks)
    out.push(
      `- [ ] The health endpoint reports \`${k}: false\` — find which environment variable or service it depends on and fix the deployment configuration (not the code).`
    );
  for (const i of missing)
    out.push(
      `- [ ] ${i.required ? "" : "(recommended) "}Set \`${i.names.join("` or `")}\` in the Dokploy application — ${i.why}`
    );

  // Site security (outside view)
  const probe = repo.siteProbe as SiteProbe | null;
  if (probe?.findings.length) {
    out.push("");
    out.push(`## 3b. Site security (${probe.findings.length})`);
    out.push("");
    for (const f of probe.findings)
      out.push(`- [ ] **${f.severity}** ${f.title} — ${f.detail} (${f.url})`);
  }

  // Performance
  const failures = d.perf ? budgetFailures(d.perf) : [];
  if (failures.length) {
    out.push("");
    out.push(
      `## 3c. Performance (mobile Lighthouse ${d.perf!.performance ?? "?"})`
    );
    out.push("");
    out.push(
      `Measured on ${d.perf!.url} (${d.perf!.createdAt.toISOString()}). Budget: the Lighthouse go-live budget (SEO 100, accessibility ≥ 95, LCP ≤ 2.5 s, CLS ≤ 0.1, TBT ≤ 300 ms, < 3 MB). Usual causes: unoptimized images, render-blocking scripts, slow server responses.`
    );
    out.push("");
    for (const f of failures) out.push(`- [ ] ${f}`);
  }

  // Live findings
  out.push("");
  const live = [...d.live].sort(
    (a, b) =>
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );
  out.push(`## 4. Running application (${live.length})`);
  out.push("");
  if (!live.length)
    out.push("No open findings on the live site and its container. ✅");
  for (const f of live.slice(0, 80))
    out.push(
      `- [ ] **${f.severity}** (${f.source}) ${f.title}${f.target ? ` — \`${f.target}\`` : ""}${f.detail ? `\n  ${f.detail.split("\n")[0]}` : ""}`
    );
  if (live.length > 80)
    out.push(`- … and ${live.length - 80} more in Moatline.`);

  // Deploy
  const dep = d.lastDeploy;
  if (
    dep &&
    (dep.guard === "broken" ||
      dep.guard === "build_failed" ||
      dep.guard === "rollback_failed" ||
      dep.liveOk === false)
  ) {
    out.push("");
    out.push("## 5. Last deploy");
    out.push("");
    out.push(
      `- [ ] The deploy of ${dep.triggeredAt.toISOString()} did not go live cleanly: ${dep.guardDetail ?? dep.liveDetail ?? dep.guard}. Reproduce with a production build (\`next build && next start\`) and check the Dokploy build log.`
    );
  }

  out.push("");
  return out.join("\n");
}

export async function buildFindingsReport(
  repositoryId: string
): Promise<string | null> {
  const [repo] = await db
    .select()
    .from(repositories)
    .where(eq(repositories.id, repositoryId));
  if (!repo) return null;
  const [scan] = await db
    .select()
    .from(scans)
    .where(
      and(eq(scans.repositoryId, repositoryId), eq(scans.status, "success"))
    )
    .orderBy(desc(scans.startedAt))
    .limit(1);
  const [perf] = await db
    .select()
    .from(perfRuns)
    .where(
      and(
        eq(perfRuns.repositoryId, repositoryId),
        eq(perfRuns.strategy, "mobile"),
        isNull(perfRuns.error)
      )
    )
    .orderBy(desc(perfRuns.createdAt))
    .limit(1);
  const [vulns, packages, live, deploys] = await Promise.all([
    scan
      ? db
          .select()
          .from(vulnerabilities)
          .where(eq(vulnerabilities.scanId, scan.id))
      : Promise.resolve([]),
    scan
      ? db
          .select()
          .from(packageFindings)
          .where(eq(packageFindings.scanId, scan.id))
      : Promise.resolve([]),
    db
      .select()
      .from(serverFindings)
      .where(
        and(
          eq(serverFindings.repositoryId, repositoryId),
          isNull(serverFindings.resolvedAt)
        )
      )
      .limit(500),
    db
      .select()
      .from(deployRuns)
      .where(eq(deployRuns.repositoryId, repositoryId))
      .orderBy(desc(deployRuns.triggeredAt))
      .limit(1),
  ]);
  return renderFindings({
    repo,
    scan: scan
      ? { startedAt: scan.startedAt, ref: scan.ref, target: scan.target }
      : null,
    vulns,
    packages,
    live,
    lastDeploy: deploys[0] ?? null,
    perf: perf ?? null,
    generatedAt: new Date(),
  });
}
